Minor test fixups
pycountry/pycountry pull request #194
Opened 2023-12-20 05:34 UTC by zware

- Catch and assert warnings in tests
- Activate mis-named tests, rewrite them for pytest
- Avoid polluting builtins with gettext.install
- Remove unused logging fixture

2023-12-20 13:38 UTC, nschimmoller commented on src/pycountry/tests/test_general.py
> +        pytest.skip("pycountry not installed correctly, you're on your own")
lmao 🤣

2023-12-20 14:05 UTC, nschimmoller requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pycountry/pycountry/194)* status: all files reviewed, 1 unresolved discussion (waiting on @zware)

___
*[`src/pycountry/tests/test_general.py` line 288 at r1](https://reviewable.io/reviews/pycountry/pycountry/194#gh-1432726333:-Nm6X2_d8QHispC72Qh2:b-xmo7hp) ([raw file](https://github.com/pycountry/pycountry/blob/5be444ca570f7704ca5bd2ab12a1d9f91770f2a8/src/pycountry/tests/test_general.py#L288)):*
<details><summary><i>Previously, nschimmoller (Nate Schimmoller) wrote…</i></summary><blockquote>

lmao 🤣
</blockquote></details>

@zware I did run this in the same fashion as #108 both with `pytest` and `make test` which uses `tox` and both passed. With the user still being required to `pip install pytest-cov` which I think is reasonable. 


<!-- Sent from Reviewable.io -->

2023-12-20 16:00 UTC, nschimmoller submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/pycountry/pycountry/194)* status: all files reviewed, 2 unresolved discussions (waiting on @zware)

___
*[`src/pycountry/tests/test_general.py` line 13 at r1](https://reviewable.io/reviews/pycountry/pycountry/194#-Nm6W3vb7ChnQtDAGxiM:-Nm6W3vcDUi_abl5qXGD:b-yaafsu) ([raw file](https://github.com/pycountry/pycountry/blob/5be444ca570f7704ca5bd2ab12a1d9f91770f2a8/src/pycountry/tests/test_general.py#L13)):*
> ```Python
> 
> 
> @pytest.fixture
> ```

@zware would love your thoughts on this. 

One of the items that I am tracking as an enhancement after we get the handful of open PRs is to add as much method consistency between instances of the Database classes. Such as:

- search_fuzzy
- add_entry
- remove_entry
- etc.

These changes seem great to ensure that after add_entry or remove_entry is ran for the. Countries class where this exists today, the instance is reset. I wonder if this is something that we should just do for all Database class test instances in this PR while it is top of mind. 

Thoughts?


<!-- Sent from Reviewable.io -->

2024-01-06 16:38 UTC, zware reviewed
> *[Reviewable](https://reviewable.io/reviews/pycountry/pycountry/194)* status: all files reviewed, 2 unresolved discussions (waiting on @nschimmoller)

___
*[`src/pycountry/tests/test_general.py` line 13 at r1](https://reviewable.io/reviews/pycountry/pycountry/194#-Nm6W3vb7ChnQtDAGxiM:-NmS73GsEX-xuYGr5XaN:b7ej4ts) ([raw file](https://github.com/pycountry/pycountry/blob/5be444ca570f7704ca5bd2ab12a1d9f91770f2a8/src/pycountry/tests/test_general.py#L13)):*
<details><summary><i>Previously, nschimmoller (Nate Schimmoller) wrote…</i></summary><blockquote>

@zware would love your thoughts on this. 

One of the items that I am tracking as an enhancement after we get the handful of open PRs is to add as much method consistency between instances of the Database classes. Such as:

- search_fuzzy
- add_entry
- remove_entry
- etc.

These changes seem great to ensure that after add_entry or remove_entry is ran for the. Countries class where this exists today, the instance is reset. I wonder if this is something that we should just do for all Database class test instances in this PR while it is top of mind. 

Thoughts?
</blockquote></details>

I think that makes sense, but I think it can wait for another PR: what I have in mind is a public global `reset()` method that clears *all* state (maybe optionally taking a class or set of classes to clear without touching others?) and make use of that in the tests rather than faking it with further fixtures.
___
*[`src/pycountry/tests/test_general.py` line 288 at r1](https://reviewable.io/reviews/pycountry/pycountry/194#gh-1432726333:-NnUd-d8CAsEj3YKIbEA:bb6mt9b) ([raw file](https://github.com/pycountry/pycountry/blob/5be444ca570f7704ca5bd2ab12a1d9f91770f2a8/src/pycountry/tests/test_general.py#L288)):*
<details><summary><i>Previously, nschimmoller (Nate Schimmoller) wrote…</i></summary><blockquote>

@zware I did run this in the same fashion as #108 both with `pytest` and `make test` which uses `tox` and both passed. With the user still being required to `pip install pytest-cov` which I think is reasonable.
</blockquote></details>

:+1:


<!-- Sent from Reviewable.io -->

2024-01-13 00:47 UTC, merged